# NOTE: update this with your service name
service: notes-serverless

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables
  - serverless-plugin-datadog

custom:
  datadog:
    forwarder: arn:aws:lambda:eu-central-1:270501904710:function:datadog-ForwarderStack-D1O6BVIL0AJO-Forwarder-2F2HTTE1B0HP

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-central-1
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  #environment:
  #  SAMPLE_ENV_VAR: ${env:SAMPLE_ENV_VAR}

functions:
  test:
    # Defines an HTTP API endpoint that calls the main function in list.js
    # - path: url path is /test
    # - method: GET request
    handler: test.main
    events:
      - http:
          path: test
          method: get

  list:
    # Defines an HTTP API endpoint that calls the main function in list.js
    # - path: url path is /notes
    # - method: GET request
    handler: list.main
    events:
      - http:
          path: notes
          method: get

  get:
    # Defines an HTTP API endpoint that calls the main function in get.js
    # - path: url path is /notes/{id}
    # - method: GET request
    handler: get.main
    events:
      - http:
          path: notes/{id}
          method: get

  create:
    # Defines an HTTP API endpoint that calls the main function in create.js
    # - path: url path is /notes
    # - method: POST request
    handler: create.main
    events:
      - http:
          path: notes
          method: post

  update:
    # Defines an HTTP API endpoint that calls the main function in create.js
    # - path: url path is /notes/{id}
    # - method: PUT request
    handler: update.main
    events:
      - http:
          path: notes/{id}
          method: put
